%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace.

% Auto-generated by MATLAB (R2025b) and Database Toolbox Version 25.2 on 24-Apr-2026 22:34:27

%% Make connection to database
conn = database('pruebaParcial');

%Set query to execute on the database
query = ['SELECT * ' ...
    'FROM matlab1104a.producto_80'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query